export const GAME_CONFIG = {
  canvasWidth: 900,
  canvasHeight: 280,
  groundY: 220,
  gravity: 1900,
  jumpStrength: 680,
  gameSpeed: 300,
  speedIncreasePerSecond: 8,
  spawnIntervalMin: 0.85,
  spawnIntervalMax: 1.5,
  minObstacleGapBase: 180,
  minObstacleGapSpeedFactor: 0.22,
  maxDeltaTime: 0.05,
  scorePerSecond: 10,
  floatingMinY: 118,
  floatingMaxY: 155,
  floatingBottomLimitPlayerHeightRatio: 0.7,
  longJumpDuration: 0.28,
  longJumpCooldown: 1.0,
  longJumpForwardSpeed: 220,
  longJumpMaxForwardOffset: 92,
  longJumpReturnSpeed: 260,
  spawnWeights: {
    groundShort: 0.55,
    groundLong: 0.25,
    floating: 0.2,
  },
  typeCooldowns: {
    groundShort: 0,
    groundLong: 0.35,
    floating: 0.9,
  },
  player: {
    x: 90,
    width: 42,
    height: 48,
    crouchHeightRatio: 0.6,
    color: '#1f2937',
  },
  obstacleStyles: {
    groundShort: '#0f766e',
    groundLong: '#115e59',
    floating: '#0369a1',
  },
  obstacle: {
    groundShort: {
      minWidth: 24,
      maxWidth: 42,
      minHeight: 32,
      maxHeight: 56,
    },
    groundLong: {
      minWidth: 64,
      maxWidth: 124,
      minHeight: 26,
      maxHeight: 42,
    },
    floating: {
      minWidth: 50,
      maxWidth: 59,
      minHeight: 49,
      maxHeight: 58,
    },
  },
  palette: {
    background: '#f4f1e8',
    ground: '#7c5f3f',
    accent: '#c2410c',
  },
}
